<?php
/**
 * ResizePresetSize
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Aspose.Pdf RestApi
 *
 * Aspose.Pdf RestApi provides a comprehensive set of endpoints for various PDF-related tasks, enabling efficient document processing and manipulation. Users can retrieve processing status, download files, manage file locks, parse documents, redact sensitive information, convert between formats, merge files, add watermarks, perform text searches, and much more. With endpoints for tasks like electronic signing, document comparison, and form filling, the API offers extensive functionality to cater to diverse PDF requirements.
 *
 * OpenAPI spec version: v1
 * Contact: Evgeny.Pirogov@aspose.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * ResizePresetSize Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ResizePresetSize
{
    /**
     * Possible values of this enum
     */
    const INSTAGRAM_STORY = 'Instagram_Story';
    const INSTAGRAM_SQUARE = 'Instagram_Square';
    const INSTAGRAM_PORTRAIT = 'Instagram_Portrait';
    const INSTAGRAM_LANDSCAPE = 'Instagram_Landscape';
    const FACEBOOK_POST = 'Facebook_Post';
    const TWITTER_POST = 'Twitter_Post';
    const YOUTUBE_THUMBNAIL = 'Youtube_Thumbnail';
    const PINTEREST_PIN = 'Pinterest_Pin';
    const LINED_IN_SHARED_IMAGE = 'LinedIn_Shared_Image';
    const SNAPCHAT_STORY = 'Snapchat_Story';
    const STANDARD_WIDESCREEN = 'Standard_Widescreen';
    const STANDARD_I_PHONE = 'Standard_iPhone';
    const STANDARD_PRESENTATION = 'Standard_Presentation';
    const STANDARD_SQUARE = 'Standard_Square';
    const STANDARD_LANDSCAPE = 'Standard_Landscape';
    const STANDARD_PORTRAIT = 'Standard_Portrait';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::INSTAGRAM_STORY
            self::INSTAGRAM_SQUARE
            self::INSTAGRAM_PORTRAIT
            self::INSTAGRAM_LANDSCAPE
            self::FACEBOOK_POST
            self::TWITTER_POST
            self::YOUTUBE_THUMBNAIL
            self::PINTEREST_PIN
            self::LINED_IN_SHARED_IMAGE
            self::SNAPCHAT_STORY
            self::STANDARD_WIDESCREEN
            self::STANDARD_I_PHONE
            self::STANDARD_PRESENTATION
            self::STANDARD_SQUARE
            self::STANDARD_LANDSCAPE
            self::STANDARD_PORTRAIT
        ];
    }
}
