<?php
/**
 * ResizePageSize
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Aspose.Pdf RestApi
 *
 * Aspose.Pdf RestApi provides a comprehensive set of endpoints for various PDF-related tasks, enabling efficient document processing and manipulation. Users can retrieve processing status, download files, manage file locks, parse documents, redact sensitive information, convert between formats, merge files, add watermarks, perform text searches, and much more. With endpoints for tasks like electronic signing, document comparison, and form filling, the API offers extensive functionality to cater to diverse PDF requirements.
 *
 * OpenAPI spec version: v1
 * Contact: Evgeny.Pirogov@aspose.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * ResizePageSize Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ResizePageSize
{
    /**
     * Possible values of this enum
     */
    const CUSTOM = 'Custom';
    const A4 = 'A4';
    const A3 = 'A3';
    const LETTER = 'Letter';
    const A5 = 'A5';
    const B5 = 'B5';
    const LEGAL = 'Legal';
    const LEDGER = 'Ledger';
    const A6 = 'A6';
    const A2 = 'A2';
    const A1 = 'A1';
    const A0 = 'A0';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CUSTOM
            self::A4
            self::A3
            self::LETTER
            self::A5
            self::B5
            self::LEGAL
            self::LEDGER
            self::A6
            self::A2
            self::A1
            self::A0
        ];
    }
}
