/**
 * Aspose.Pdf RestApi
 * Demo 1
 *
 * OpenAPI spec version: v1
 * Contact: Evgeny.Pirogov@aspose.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.FileProcessingErrorCode
import io.swagger.client.models.FileSafeResult

/**
 * 
 * @param statusCode 
 * @param status 
 * @param text 
 * @param locked 
 * @param updated Last updated
 * @param sharedFiles 
 * @param files 
 * @param fileProcessingErrorCode 
 * @param fileCount Get count of files
 * @param fileName 
 * @param folderName 
 * @param resultData 
 * @param appInstanceId Where is processing located
 */
data class FileResponse (

    val statusCode: kotlin.Int? = null,
    val status: kotlin.String? = null,
    val text: kotlin.String? = null,
    val locked: kotlin.Boolean? = null,
    /* Last updated */
    val updated: java.time.LocalDateTime? = null,
    val sharedFiles: kotlin.Array<FileSafeResult>? = null,
    val files: kotlin.Array<kotlin.String>? = null,
    val fileProcessingErrorCode: FileProcessingErrorCode? = null,
    /* Get count of files */
    val fileCount: kotlin.Int? = null,
    val fileName: kotlin.String? = null,
    val folderName: kotlin.String? = null,
    val resultData: kotlin.Any? = null,
    /* Where is processing located */
    val appInstanceId: kotlin.String? = null
) {
}