/**
 * Aspose.Pdf RestApi
 * Demo 1
 *
 * OpenAPI spec version: v1
 * Contact: Evgeny.Pirogov@aspose.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * Values: _0,_10000,_10001,_10002
 */
enum class FileProcessingErrorCode(val value: kotlin.Int){
    _0(0),// :/
    _10000(10000),// :/
    _10001(10001),// :/
    _10002(10002);// :/
}