/**
 * Aspose.Pdf RestApi
 * Demo 1
 *
 * OpenAPI spec version: v1
 * Contact: Evgeny.Pirogov@aspose.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * Values: _0,_1,_2,_3,_4,_5,_6,_7,_8
 */
enum class PropertyType(val value: kotlin.Int){
    _0(0),// :/
    _1(1),// :/
    _2(2),// :/
    _3(3),// :/
    _4(4),// :/
    _5(5),// :/
    _6(6),// :/
    _7(7),// :/
    _8(8);// :/
}