/**
 * Aspose.Pdf RestApi
 * Demo 1
 *
 * OpenAPI spec version: v1
 * Contact: Evgeny.Pirogov@aspose.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param watermarkText 
 * @param top 
 * @param left 
 * @param bottom 
 * @param right 
 * @param files 
 */
data class WebapiRemovewatermarkBody (

    val watermarkText: kotlin.String? = null,
    val top: kotlin.Int? = null,
    val left: kotlin.Int? = null,
    val bottom: kotlin.Int? = null,
    val right: kotlin.Int? = null,
    val files: kotlin.Array<kotlin.Array<kotlin.Byte>>? = null
) {
}