/*
 * Aspose.Pdf RestApi
 * Demo 1
 *
 * OpenAPI spec version: v1
 * Contact: Evgeny.Pirogov@aspose.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets FileProcessingErrorCode
 */
@JsonAdapter(FileProcessingErrorCode.Adapter.class)
public enum FileProcessingErrorCode {
  @SerializedName("0")
  NUMBER_0(0),
  @SerializedName("10000")
  NUMBER_10000(10000),
  @SerializedName("10001")
  NUMBER_10001(10001),
  @SerializedName("10002")
  NUMBER_10002(10002);

  private Integer value;

  FileProcessingErrorCode(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static FileProcessingErrorCode fromValue(Integer input) {
    for (FileProcessingErrorCode b : FileProcessingErrorCode.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<FileProcessingErrorCode> {
    @Override
    public void write(final JsonWriter jsonWriter, final FileProcessingErrorCode enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public FileProcessingErrorCode read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextInt();
      return FileProcessingErrorCode.fromValue((Integer)(value));
    }
  }
}
