<?php
/**
 * FileResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Aspose.Pdf RestApi
 *
 * Demo 1
 *
 * OpenAPI spec version: v1
 * Contact: Evgeny.Pirogov@aspose.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * FileResponseTest Class Doc Comment
 *
 * @category    Class
 * @description FileResponse
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FileResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FileResponse"
     */
    public function testFileResponse()
    {
    }

    /**
     * Test attribute "status_code"
     */
    public function testPropertyStatusCode()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "text"
     */
    public function testPropertyText()
    {
    }

    /**
     * Test attribute "locked"
     */
    public function testPropertyLocked()
    {
    }

    /**
     * Test attribute "updated"
     */
    public function testPropertyUpdated()
    {
    }

    /**
     * Test attribute "shared_files"
     */
    public function testPropertySharedFiles()
    {
    }

    /**
     * Test attribute "files"
     */
    public function testPropertyFiles()
    {
    }

    /**
     * Test attribute "file_processing_error_code"
     */
    public function testPropertyFileProcessingErrorCode()
    {
    }

    /**
     * Test attribute "file_count"
     */
    public function testPropertyFileCount()
    {
    }

    /**
     * Test attribute "file_name"
     */
    public function testPropertyFileName()
    {
    }

    /**
     * Test attribute "folder_name"
     */
    public function testPropertyFolderName()
    {
    }

    /**
     * Test attribute "result_data"
     */
    public function testPropertyResultData()
    {
    }

    /**
     * Test attribute "app_instance_id"
     */
    public function testPropertyAppInstanceId()
    {
    }
}
