<?php
/**
 * WebapiWatermarkBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Aspose.Pdf RestApi
 *
 * Demo 1
 *
 * OpenAPI spec version: v1
 * Contact: Evgeny.Pirogov@aspose.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * WebapiWatermarkBodyTest Class Doc Comment
 *
 * @category    Class
 * @description WebapiWatermarkBody
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WebapiWatermarkBodyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "WebapiWatermarkBody"
     */
    public function testWebapiWatermarkBody()
    {
    }

    /**
     * Test attribute "is_text"
     */
    public function testPropertyIsText()
    {
    }

    /**
     * Test attribute "text"
     */
    public function testPropertyText()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {
    }

    /**
     * Test attribute "bold"
     */
    public function testPropertyBold()
    {
    }

    /**
     * Test attribute "italic"
     */
    public function testPropertyItalic()
    {
    }

    /**
     * Test attribute "underlined"
     */
    public function testPropertyUnderlined()
    {
    }

    /**
     * Test attribute "color"
     */
    public function testPropertyColor()
    {
    }

    /**
     * Test attribute "content_type"
     */
    public function testPropertyContentType()
    {
    }

    /**
     * Test attribute "content_disposition"
     */
    public function testPropertyContentDisposition()
    {
    }

    /**
     * Test attribute "headers"
     */
    public function testPropertyHeaders()
    {
    }

    /**
     * Test attribute "length"
     */
    public function testPropertyLength()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "file_name"
     */
    public function testPropertyFileName()
    {
    }

    /**
     * Test attribute "is_background"
     */
    public function testPropertyIsBackground()
    {
    }

    /**
     * Test attribute "rotation"
     */
    public function testPropertyRotation()
    {
    }

    /**
     * Test attribute "transparency"
     */
    public function testPropertyTransparency()
    {
    }

    /**
     * Test attribute "layer"
     */
    public function testPropertyLayer()
    {
    }

    /**
     * Test attribute "page_from"
     */
    public function testPropertyPageFrom()
    {
    }

    /**
     * Test attribute "page_to"
     */
    public function testPropertyPageTo()
    {
    }

    /**
     * Test attribute "files"
     */
    public function testPropertyFiles()
    {
    }
}
