/*
 * Aspose.Pdf RestApi
 *
 * Demo 1
 *
 * OpenAPI spec version: v1
 * Contact: Evgeny.Pirogov@aspose.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
  
          /// <summary>
          /// Gets or Sets FileProcessingErrorCode
          /// </summary>
          [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
          public enum FileProcessingErrorCode
          {
              /// <summary>
              /// Enum NUMBER_0 for 0
              /// </summary>
              [EnumMember(Value = "0")]
              NUMBER_0 = 0,
              /// <summary>
              /// Enum NUMBER_10000 for 10000
              /// </summary>
              [EnumMember(Value = "10000")]
              NUMBER_10000 = 1,
              /// <summary>
              /// Enum NUMBER_10001 for 10001
              /// </summary>
              [EnumMember(Value = "10001")]
              NUMBER_10001 = 2,
              /// <summary>
              /// Enum NUMBER_10002 for 10002
              /// </summary>
              [EnumMember(Value = "10002")]
              NUMBER_10002 = 3          }
}
