<?php
/**
 * FileSafeResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Aspose.Pdf RestApi
 *
 * Demo 1
 *
 * OpenAPI spec version: v1
 * Contact: Evgeny.Pirogov@aspose.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * FileSafeResultTest Class Doc Comment
 *
 * @category    Class
 * @description File processing result.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FileSafeResultTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FileSafeResult"
     */
    public function testFileSafeResult()
    {
    }

    /**
     * Test attribute "is_success"
     */
    public function testPropertyIsSuccess()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "file_name"
     */
    public function testPropertyFileName()
    {
    }

    /**
     * Test attribute "upload_file_name"
     */
    public function testPropertyUploadFileName()
    {
    }

    /**
     * Test attribute "id_upload"
     */
    public function testPropertyIdUpload()
    {
    }

    /**
     * Test attribute "file_length"
     */
    public function testPropertyFileLength()
    {
    }

    /**
     * Test attribute "built_prop"
     */
    public function testPropertyBuiltProp()
    {
    }

    /**
     * Test attribute "custom_prop"
     */
    public function testPropertyCustomProp()
    {
    }
}
