<?php
/**
 * WebapiRemovewatermarkBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Aspose.Pdf RestApi
 *
 * Demo 1
 *
 * OpenAPI spec version: v1
 * Contact: Evgeny.Pirogov@aspose.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * WebapiRemovewatermarkBodyTest Class Doc Comment
 *
 * @category    Class
 * @description WebapiRemovewatermarkBody
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WebapiRemovewatermarkBodyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "WebapiRemovewatermarkBody"
     */
    public function testWebapiRemovewatermarkBody()
    {
    }

    /**
     * Test attribute "watermark_text"
     */
    public function testPropertyWatermarkText()
    {
    }

    /**
     * Test attribute "top"
     */
    public function testPropertyTop()
    {
    }

    /**
     * Test attribute "left"
     */
    public function testPropertyLeft()
    {
    }

    /**
     * Test attribute "bottom"
     */
    public function testPropertyBottom()
    {
    }

    /**
     * Test attribute "right"
     */
    public function testPropertyRight()
    {
    }

    /**
     * Test attribute "files"
     */
    public function testPropertyFiles()
    {
    }
}
